alias: Update Current Track Favorite Status
description: Checks if the currently playing track is favorited in Music Assistant
triggers:
  - entity_id: media_player.<media player id>
    attribute: media_title
    trigger: state
  - entity_id: button.<media player id>_favorite_current_song
    trigger: state
conditions:
  - condition: template
    value_template: >-
      {{ state_attr('media_player.<media player id>', 'media_title') not in
      ['unknown', 'unavailable', None] }}
actions:
  - data:
      limit: 25
      config_entry_id: <config entry id>
      media_type: track
      search: "{{ state_attr('media_player.<media player id>', 'media_title') }}"
    response_variable: track_results
    action: music_assistant.get_library
  - variables:
      current_artist: "{{ state_attr('media_player.<media player id>', 'media_artist') }}"
      current_album: "{{ state_attr('media_player.<media player id>', 'media_album_name') }}"
      matching_favorite: >
        {% set ns = namespace(found=false) %} {% for item in
        track_results['items'] %}
          {% if item.favorite == true %}
            {% set artist_match = item.artists | selectattr('name', 'eq', current_artist) | list | length > 0 %}
            {% set album_match = item.album.name | lower | replace(' ', '') == current_album | lower | replace(' ', '') %}
            {% if artist_match and album_match %}
              {% set ns.found = true %}
            {% endif %}
          {% endif %}
        {% endfor %} {{ ns.found }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ matching_favorite == true }}"
        sequence:
          - target:
              entity_id: input_boolean.current_track_is_favorite
            action: input_boolean.turn_on
    default:
      - target:
          entity_id: input_boolean.current_track_is_favorite
        action: input_boolean.turn_off
